receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: 0.0.0.0:4317

exporters:
  logging:
    loglevel: debug

extensions:
  health_check:
  pprof:

service:
  extensions: [health_check, pprof]
  pipelines:
    traces:
      receivers: [otlp]
      processors: []
      exporters: [logging]
    metrics:
      receivers: [otlp]
      processors: []
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: []
      exporters: [logging]
